### ISSUE TITLE
kicad6

### ISSUE THREAD

**Issue by shachooo** [asukiaaa/gerber_to_order#5]
便利なので使わせてもらっています
kicad6リリースしたので、試してみたところ、エラーが出ました
apiの変更の為、いくつかエラーが出ます
エラー内容は省きますが
以下のようにしたところ、エラーが出なくなりました
問題ないでしょうか？
outline_measure.py

![01](https://user-images.githubusercontent.com/96701193/147507028-210a172e-a672-411f-98a5-4b788f35666c.png)

gerber_to_order_action.py
![02](https://user-images.githubusercontent.com/96701193/147507254-9e1b7e12-6458-4066-8ce7-4d12e48dd218.png)

![03](https://user-images.githubusercontent.com/96701193/147507260-c84fca3c-68cc-435d-a5bb-bf2de47360b3.png)

よろしくお願いいたします

**Comment by asukiaaa** [comment]
不具合情報ありがとうございます。
pull requestを作成していただけますか？

**Comment by odaki** [comment]
ブランチを切ってKiCad6対応してみました。
ただし、現状、KiCad5とは互換性がなくなる書き方なので pull request はしておりません。
https://github.com/odaki/gerber_to_order/tree/kicad6

**Comment by odaki** [comment]
https://github.com/yaqwsx/pcbnewTransition
のisV6()のようなものを用意して、5.xと6.xの両対応するのがベターかと思いつつも、そこまでできておりません。

**Comment by shachooo** [comment]
ありがとうございます
使ってみます

**Comment by odaki** [comment]
@asukiaaa @shachooo KiCad 6 (5.99～)と、KiCad 5の両方に対応できるように修正してみました。
よろしければマージをお願いします。
Support both KiCad 5 and KiCad 6 https://github.com/asukiaaa/gerber_to_order/pull/6

**Comment by asukiaaa** [comment]
ご対応ありがとうございます。
マージしました。

**Comment by odaki** [comment]
マージいただきどうもありがとうございました!
issue #4 の対策にもなっているはずです。
